# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
x=np.random.random((3,3,3))
print(x)

[[[0.45934209 0.13189443 0.5948871 ]
  [0.54631627 0.65937683 0.92677541]
  [0.96934282 0.15001706 0.45888322]]

 [[0.58103442 0.12672428 0.03622013]
  [0.99430474 0.94012332 0.17094448]
  [0.88422238 0.08662212 0.44740541]]

 [[0.78951744 0.49319309 0.66787725]
  [0.21520233 0.42241257 0.52950171]
  [0.37122184 0.0828593  0.30424573]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
np.diag([1,2,3,4],-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [5]:
x= np.random.random((3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.11903648 0.01161008 0.11502287]
 [0.50464424 0.10631024 0.93020761]
 [0.34194166 0.76032329 0.72879165]]
After normalization:
[[0.1169461  0.         0.11257682]
 [0.53672489 0.10309211 1.        ]
 [0.35960426 0.8150612  0.78073535]]


# 5.  How to find common values between two arrays?

# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [7]:
a=np.random.random((3,3))
b=np.random.random((3,3))
print(a);print(b)
c = np.allclose(a, b)
print("Arrays are equal:")
print(c)

[[0.91512562 0.44127536 0.63184884]
 [0.3652157  0.64192766 0.77545514]
 [0.15560127 0.65434142 0.39380381]]
[[0.9119146  0.6588288  0.70469893]
 [0.25220244 0.58962051 0.86991415]
 [0.26864883 0.40204541 0.59589374]]
Arrays are equal:
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = -100
print("Replace maximum value by -100:")
print(x)

Original array:
[0.8486087  0.73779735 0.39727632 0.92932892 0.51795425 0.34115708
 0.83208868 0.02029098 0.69501226 0.40648727]
Replace maximum value by -100:
[ 8.48608701e-01  7.37797351e-01  3.97276316e-01 -1.00000000e+02
  5.17954255e-01  3.41157080e-01  8.32088679e-01  2.02909801e-02
  6.95012261e-01  4.06487266e-01]


# 9. How to print all the values of an array?

In [ ]:
x=[[1,2,3,4,5],[6,7,8,9,0]]
print(x)

# 10.Subtract the mean of each row of a matrix

In [9]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(3,3)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1)
print(Y)

Original matrix:

[[0.863095   0.81470207 0.65468164]
 [0.34626826 0.8786051  0.75559906]
 [0.84104304 0.15943194 0.51360314]]

Subtract the mean of each row of the said matrix:

[[ 0.08560209  0.1545446   0.14998893]
 [-0.43122465  0.21844763  0.25090636]
 [ 0.06355013 -0.50072553  0.00891043]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

# 12.How to get the diagonal of a dot product?

In [ ]:
x=np.array([4,5])
y=np.array([6,7])
print(x.dot(y))
print(np.dot(x,y))

# 13.How to find the most frequent value in an array?

In [ ]:
x = np.random.randint(0, 10, 20)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

# 14.How to get the n largest values of an array

In [ ]:
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

# 15.How to create a record array from a regular array?

In [ ]:
arra1 = np.array([("xyz", 88.5, 90),("abc", 87, 99),("pqr", 85.5, 91)])
print("Original array:")
print(arra1)
print("\nRecord array:")
result = np.core.records.fromarrays(arra1.T,names='col1, col2, col3',formats = 'S80, f8, i8')
print(result)
